/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Petstore
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const BASE_PATH = "http://petstore.swagger.io/v2".replace(/\/+$/, "");

export class RequiredError extends Error {
    name: "RequiredError" = "RequiredError";
    constructor(public field: string, msg?: string) {
        super(msg);
    }
}

export const COLLECTION_FORMATS = {
    csv:   ",",
    ssv:   " ",
    tsv:   "\t",
    pipes: "|",
};

export type HttpHeaders = { [key: string]: string };

export type ModelPropertyNaming = 'camelCase' | 'snake_case' | 'PascalCase' | 'original';

export interface ConfigurationParameters {
    basePath?: string;
    username?: string;
    password?: string;
    apiKey?: string | ((name: string) => string);
    accessToken?: string | ((name?: string, scopes?: string[]) => string);
    headers?: HttpHeaders;
}

export class Configuration {
    constructor(private configuration: ConfigurationParameters = {}) {}

    set config(configuration: Configuration) {
        this.configuration = configuration;
    }

    get basePath(): string {
        return this.configuration.basePath != null ? this.configuration.basePath : BASE_PATH;
    }

    get username(): string | undefined {
        return this.configuration.username;
    }

    get password(): string | undefined {
        return this.configuration.password;
    }

    get apiKey(): ((name: string) => string) | undefined {
        const apiKey = this.configuration.apiKey;
        if (apiKey) {
            return typeof apiKey === 'function' ? apiKey : () => apiKey;
        }
        return undefined;
    }

    get accessToken(): ((name?: string, scopes?: string[]) => string) | undefined {
        const accessToken = this.configuration.accessToken;
        if (accessToken) {
            return typeof accessToken === 'function' ? accessToken : () => accessToken;
        }
        return undefined;
    }

    get headers(): HttpHeaders | undefined {
        return this.configuration.headers;
    }
}

export const DefaultConfig = new Configuration();

export function exists(json: any, key: string): boolean {
    const value = json[key];
    return value !== null && value !== undefined;
}

export function mapValues(data: any, fn: (item: any) => any): any {
    return Object.keys(data).reduce(
        (acc, key) => ({ ...acc, [key]: fn(data[key]) }),
        {}
    );
}

export function canConsumeForm(consumes: { contentType: string }[]): boolean {
    for (const consume of consumes) {
        if ('multipart/form-data' === consume.contentType) {
            return true;
        }
    }
    return false;
}

/**
 * Standard BFF error response shape.
 * BFF always returns HTTP 200, but wraps server errors in this payload.
 */
export interface BffErrorResponse {
    type: string | null;
    title: string | null;
    status: number;
    detail: string | null;
    instance: string | null;
    data: unknown | null;
    metaData: unknown | null;
}

export function isBffError(response: unknown): response is BffErrorResponse {
    return (
        typeof response === 'object' &&
        response !== null &&
        'status' in response &&
        typeof (response as any).status === 'number' &&
        (response as any).status >= 400
    );
}
