/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Petstore
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';
import type { BaseQueryFn, FetchArgs, FetchBaseQueryError } from '@reduxjs/toolkit/query';
import { Configuration, DefaultConfig } from '../runtime';

const baseQuery: BaseQueryFn<FetchArgs, unknown, FetchBaseQueryError> = async (args: FetchArgs, api: any, extraOptions: { configuration?: Configuration }) => {
    const configuration = extraOptions?.configuration || DefaultConfig;
    const rawBaseQuery = fetchBaseQuery({
        baseUrl: configuration.basePath,
        prepareHeaders: (headers) => {
            if (configuration.username !== undefined || configuration.password !== undefined) {
                headers.set('Authorization', 'Basic ' + btoa(configuration.username + ':' + configuration.password));
            }
            if (configuration.accessToken) {
                headers.set('Authorization', `Bearer ${configuration.accessToken()}`);
            }
            if (configuration.apiKey) {
                headers.set('api_key', configuration.apiKey('api_key'));
            }
            if (configuration.headers) {
                Object.entries(configuration.headers).forEach(([key, value]) => {
                    headers.set(key, value);
                });
            }
            return headers;
        },
    });
    return rawBaseQuery(args, api, extraOptions);
};

export const api = createApi({
    reducerPath: 'api',
    baseQuery,
    tagTypes: ['Pet', 'Store', 'User'],
    endpoints: () => ({}),
});

export * from './PetApi';
export * from './StoreApi';
export * from './UserApi';
