/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Petstore
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';
import type { BaseQueryFn, FetchArgs, FetchBaseQueryError } from '@reduxjs/toolkit/query';
import * as runtime from '../runtime';
import type {
    ModelApiResponse,
    Pet,
} from '../models/index';
import {
    ModelApiResponseFromJSON,
    ModelApiResponseToJSON,
    PetFromJSON,
    PetToJSON,
} from '../models/index';

export interface AddPetRequest {
    body: Pet;
}

export interface DeletePetRequest {
    petId: number;
    apiKey?: string;
}

export interface FindPetsByStatusRequest {
    status: Array<FindPetsByStatusStatusEnum>;
}

export interface FindPetsByTagsRequest {
    tags: Array<string>;
}

export interface GetPetByIdRequest {
    petId: number;
}

export interface UpdatePetRequest {
    body: Pet;
}

export interface UpdatePetWithFormRequest {
    petId: number;
    name?: string;
    status?: string;
}

export interface UploadFileRequest {
    petId: number;
    additionalMetadata?: string;
    file?: Blob;
}


export const PetApi = createApi({
    reducerPath: 'petApi',
    baseQuery: fetchBaseQuery({
        baseUrl: runtime.BASE_PATH,
        prepareHeaders: (headers, { getState }) => {
            return runtime.prepareHeaders(headers);
        },
    }) as BaseQueryFn<FetchArgs, unknown, FetchBaseQueryError>,
    tagTypes: ['Pet'],
    endpoints: (builder) => ({
        /**
         * Add a new pet to the store
         */
        addPet: builder.mutation<void, AddPetRequest>({
            query: ({ body }) => {
                if (body === null || body === undefined) {
                    throw new runtime.RequiredError('body', 'Required parameter body was null or undefined when calling addPet.');
                }


                const headerParameters: runtime.HttpHeaders = {};
                headerParameters['Content-Type'] = 'application/json';


                return {
                    url: `/pet`,
                    method: 'POST',
                    headers: headerParameters,
                    body: PetToJSON(body),
                };
            },
        }),
        /**
         * Deletes a pet
         */
        deletePet: builder.mutation<void, DeletePetRequest>({
            query: ({ petId, apiKey }) => {
                if (petId === null || petId === undefined) {
                    throw new runtime.RequiredError('petId', 'Required parameter petId was null or undefined when calling deletePet.');
                }


                const headerParameters: runtime.HttpHeaders = {};
                if (apiKey !== undefined && apiKey !== null) {
                    headerParameters['api_key'] = String(apiKey);
                }


                return {
                    url: `/pet/{petId}`.replace('petId', encodeURIComponent(String(petId))),
                    method: 'DELETE',
                    headers: headerParameters,
                };
            },
        }),
        /**
         * Multiple status values can be provided with comma separated strings
         * Finds Pets by status
         */
        findPetsByStatus: builder.query<Array<Pet>, FindPetsByStatusRequest>({
            query: ({ status }) => {
                if (status === null || status === undefined) {
                    throw new runtime.RequiredError('status', 'Required parameter status was null or undefined when calling findPetsByStatus.');
                }

                const queryParameters: Record<string, any> = {};
                if (status !== undefined && status !== null) {
                    queryParameters['status'] = status?.join(runtime.COLLECTION_FORMATS["csv"]);
                }

                const headerParameters: runtime.HttpHeaders = {};


                return {
                    url: `/pet/findByStatus`,
                    method: 'GET',
                    headers: headerParameters,
                    params: queryParameters,
                };
            },
            transformResponse: (response: unknown) => {
                return (response as any[]).map(PetFromJSON);
            },
        }),
        /**
         * Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
         * Finds Pets by tags
         */
        findPetsByTags: builder.query<Array<Pet>, FindPetsByTagsRequest>({
            query: ({ tags }) => {
                if (tags === null || tags === undefined) {
                    throw new runtime.RequiredError('tags', 'Required parameter tags was null or undefined when calling findPetsByTags.');
                }

                const queryParameters: Record<string, any> = {};
                if (tags !== undefined && tags !== null) {
                    queryParameters['tags'] = tags?.join(runtime.COLLECTION_FORMATS["csv"]);
                }

                const headerParameters: runtime.HttpHeaders = {};


                return {
                    url: `/pet/findByTags`,
                    method: 'GET',
                    headers: headerParameters,
                    params: queryParameters,
                };
            },
            transformResponse: (response: unknown) => {
                return (response as any[]).map(PetFromJSON);
            },
        }),
        /**
         * Returns a single pet
         * Find pet by ID
         */
        getPetById: builder.query<Pet, GetPetByIdRequest>({
            query: ({ petId }) => {
                if (petId === null || petId === undefined) {
                    throw new runtime.RequiredError('petId', 'Required parameter petId was null or undefined when calling getPetById.');
                }


                const headerParameters: runtime.HttpHeaders = {};


                return {
                    url: `/pet/{petId}`.replace('petId', encodeURIComponent(String(petId))),
                    method: 'GET',
                    headers: headerParameters,
                };
            },
            transformResponse: (response: unknown) => {
                return PetFromJSON(response);
            },
        }),
        /**
         * Update an existing pet
         */
        updatePet: builder.mutation<void, UpdatePetRequest>({
            query: ({ body }) => {
                if (body === null || body === undefined) {
                    throw new runtime.RequiredError('body', 'Required parameter body was null or undefined when calling updatePet.');
                }


                const headerParameters: runtime.HttpHeaders = {};
                headerParameters['Content-Type'] = 'application/json';


                return {
                    url: `/pet`,
                    method: 'PUT',
                    headers: headerParameters,
                    body: PetToJSON(body),
                };
            },
        }),
        /**
         * Updates a pet in the store with form data
         */
        updatePetWithForm: builder.mutation<void, UpdatePetWithFormRequest>({
            query: ({ petId, name, status }) => {
                if (petId === null || petId === undefined) {
                    throw new runtime.RequiredError('petId', 'Required parameter petId was null or undefined when calling updatePetWithForm.');
                }


                const headerParameters: runtime.HttpHeaders = {};

                const formData = new FormData();
                if (name !== undefined) {
                    formData.append('name', name as any);
                }
                if (status !== undefined) {
                    formData.append('status', status as any);
                }

                return {
                    url: `/pet/{petId}`.replace('petId', encodeURIComponent(String(petId))),
                    method: 'POST',
                    headers: headerParameters,
                    body: formData,
                };
            },
        }),
        /**
         * uploads an image
         */
        uploadFile: builder.mutation<ModelApiResponse, UploadFileRequest>({
            query: ({ petId, additionalMetadata, file }) => {
                if (petId === null || petId === undefined) {
                    throw new runtime.RequiredError('petId', 'Required parameter petId was null or undefined when calling uploadFile.');
                }


                const headerParameters: runtime.HttpHeaders = {};

                const formData = new FormData();
                if (additionalMetadata !== undefined) {
                    formData.append('additionalMetadata', additionalMetadata as any);
                }
                if (file !== undefined) {
                    formData.append('file', file as any);
                }

                return {
                    url: `/pet/{petId}/uploadImage`.replace('petId', encodeURIComponent(String(petId))),
                    method: 'POST',
                    headers: headerParameters,
                    body: formData,
                };
            },
        }),
    }),
});

export const {
    useAddPetMutation,
    useDeletePetMutation,
    useFindPetsByStatusQuery,
    useFindPetsByTagsQuery,
    useGetPetByIdQuery,
    useUpdatePetMutation,
    useUpdatePetWithFormMutation,
    useUploadFileMutation,
} = PetApi;

/**
 * @export
 * @enum {string}
 */
export enum FindPetsByStatusStatusEnum {
    Available = 'available',
    Pending = 'pending',
    Sold = 'sold'
}


