/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Petstore
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';
import type { BaseQueryFn, FetchArgs, FetchBaseQueryError } from '@reduxjs/toolkit/query';
import * as runtime from '../runtime';
import { Configuration, DefaultConfig } from '../runtime';
import type {
    ModelApiResponse,
    Pet,
} from '../models/index';
import {
    ModelApiResponseFromJSON,
    ModelApiResponseToJSON,
    PetFromJSON,
    PetToJSON,
} from '../models/index';

export interface AddPetRequest {
    body: Pet;
}

export interface DeletePetRequest {
    petId: number;
    apiKey?: string;
}

export interface FindPetsByStatusRequest {
    status: Array<FindPetsByStatusStatusEnum>;
}

export interface FindPetsByTagsRequest {
    tags: Array<string>;
}

export interface GetPetByIdRequest {
    petId: number;
}

export interface UpdatePetRequest {
    body: Pet;
}

export interface UpdatePetWithFormRequest {
    petId: number;
    name?: string;
    status?: string;
}

export interface UploadFileRequest {
    petId: number;
    additionalMetadata?: string;
    file?: Blob;
}


const petApiBaseQuery: BaseQueryFn<FetchArgs, unknown, FetchBaseQueryError> = async (args: FetchArgs, api: any, extraOptions: { configuration?: Configuration }) => {
    const configuration = extraOptions?.configuration || DefaultConfig;
    const rawBaseQuery = fetchBaseQuery({
        baseUrl: configuration.basePath,
        prepareHeaders: (headers) => {
            if (configuration.username !== undefined || configuration.password !== undefined) {
                headers.set('Authorization', 'Basic ' + btoa(configuration.username + ':' + configuration.password));
            }
            if (configuration.accessToken) {
                headers.set('Authorization', `Bearer ${configuration.accessToken()}`);
            }
            if (configuration.apiKey) {
                headers.set('api_key', configuration.apiKey('api_key'));
            }
            if (configuration.headers) {
                Object.entries(configuration.headers).forEach(([key, value]) => {
                    headers.set(key, value);
                });
            }
            return headers;
        },
    });
    return rawBaseQuery(args, api, extraOptions);
};

export const PetApi = createApi({
    reducerPath: 'petApi',
    baseQuery: petApiBaseQuery,
    tagTypes: ['Pet'],
    endpoints: (builder) => ({
        /**
         * Add a new pet to the store
         */
        addPet: builder.mutation<void, AddPetRequest>({
            query: ({ body }) => {

                const headerParameters: runtime.HttpHeaders = {};
                headerParameters['Content-Type'] = 'application/json';


                return {
                    url: `/pet`,
                    method: 'POST',
                    headers: headerParameters,
                    body: PetToJSON(body),
                };
            },
            invalidatesTags: ['Pet'],
        }),
        /**
         * Deletes a pet
         */
        deletePet: builder.mutation<void, DeletePetRequest>({
            query: ({ petId, apiKey }) => {

                const headerParameters: runtime.HttpHeaders = {};
                if (apiKey !== undefined && apiKey !== null) {
                    headerParameters['api_key'] = String(apiKey);
                }


                return {
                    url: `/pet/{petId}`.replace('{petId}', encodeURIComponent(String(petId))),
                    method: 'DELETE',
                    headers: headerParameters,
                };
            },
            invalidatesTags: ['Pet'],
        }),
        /**
         * Multiple status values can be provided with comma separated strings
         * Finds Pets by status
         */
        findPetsByStatus: builder.query<Array<Pet>, FindPetsByStatusRequest>({
            query: ({ status }) => {

                const queryParameters: Record<string, any> = {};
                if (status !== undefined && status !== null) {
                    queryParameters['status'] = status?.join(runtime.COLLECTION_FORMATS["csv"]);
                }

                const headerParameters: runtime.HttpHeaders = {};


                return {
                    url: `/pet/findByStatus`,
                    method: 'GET',
                    headers: headerParameters,
                    params: queryParameters,
                };
            },
            providesTags: ['Pet'],
        }),
        /**
         * Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
         * Finds Pets by tags
         */
        findPetsByTags: builder.query<Array<Pet>, FindPetsByTagsRequest>({
            query: ({ tags }) => {

                const queryParameters: Record<string, any> = {};
                if (tags !== undefined && tags !== null) {
                    queryParameters['tags'] = tags?.join(runtime.COLLECTION_FORMATS["csv"]);
                }

                const headerParameters: runtime.HttpHeaders = {};


                return {
                    url: `/pet/findByTags`,
                    method: 'GET',
                    headers: headerParameters,
                    params: queryParameters,
                };
            },
            providesTags: ['Pet'],
        }),
        /**
         * Returns a single pet
         * Find pet by ID
         */
        getPetById: builder.query<Pet, GetPetByIdRequest>({
            query: ({ petId }) => {

                const headerParameters: runtime.HttpHeaders = {};


                return {
                    url: `/pet/{petId}`.replace('{petId}', encodeURIComponent(String(petId))),
                    method: 'GET',
                    headers: headerParameters,
                };
            },
            providesTags: ['Pet'],
        }),
        /**
         * Update an existing pet
         */
        updatePet: builder.mutation<void, UpdatePetRequest>({
            query: ({ body }) => {

                const headerParameters: runtime.HttpHeaders = {};
                headerParameters['Content-Type'] = 'application/json';


                return {
                    url: `/pet`,
                    method: 'PUT',
                    headers: headerParameters,
                    body: PetToJSON(body),
                };
            },
            invalidatesTags: ['Pet'],
        }),
        /**
         * Updates a pet in the store with form data
         */
        updatePetWithForm: builder.mutation<void, UpdatePetWithFormRequest>({
            query: ({ petId, name, status }) => {

                const headerParameters: runtime.HttpHeaders = {};

                const formData = new FormData();
                if (name !== undefined) {
                    formData.append('name', name as any);
                }
                if (status !== undefined) {
                    formData.append('status', status as any);
                }

                return {
                    url: `/pet/{petId}`.replace('{petId}', encodeURIComponent(String(petId))),
                    method: 'POST',
                    headers: headerParameters,
                    body: formData,
                };
            },
            invalidatesTags: ['Pet'],
        }),
        /**
         * uploads an image
         */
        uploadFile: builder.mutation<ModelApiResponse, UploadFileRequest>({
            query: ({ petId, additionalMetadata, file }) => {

                const headerParameters: runtime.HttpHeaders = {};

                const formData = new FormData();
                if (additionalMetadata !== undefined) {
                    formData.append('additionalMetadata', additionalMetadata as any);
                }
                if (file !== undefined) {
                    formData.append('file', file as any);
                }

                return {
                    url: `/pet/{petId}/uploadImage`.replace('{petId}', encodeURIComponent(String(petId))),
                    method: 'POST',
                    headers: headerParameters,
                    body: formData,
                };
            },
            invalidatesTags: ['Pet'],
        }),
    }),
});

export const {
    useAddPetMutation,
    useDeletePetMutation,
    useFindPetsByStatusQuery,
    useFindPetsByTagsQuery,
    useGetPetByIdQuery,
    useUpdatePetMutation,
    useUpdatePetWithFormMutation,
    useUploadFileMutation,
} = PetApi;

/**
 * @export
 * @enum {string}
 */
export enum FindPetsByStatusStatusEnum {
    Available = 'available',
    Pending = 'pending',
    Sold = 'sold'
}
