/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Petstore
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';
import type { BaseQueryFn, FetchArgs, FetchBaseQueryError } from '@reduxjs/toolkit/query';
import * as runtime from '../runtime';
import type {
    Order,
} from '../models/index';
import {
    OrderFromJSON,
    OrderToJSON,
} from '../models/index';

export interface DeleteOrderRequest {
    orderId: string;
}

export interface GetOrderByIdRequest {
    orderId: number;
}

export interface PlaceOrderRequest {
    body: Order;
}


export const StoreApi = createApi({
    reducerPath: 'storeApi',
    baseQuery: fetchBaseQuery({
        baseUrl: runtime.BASE_PATH,
        prepareHeaders: (headers, { getState }) => {
            return runtime.prepareHeaders(headers);
        },
    }) as BaseQueryFn<FetchArgs, unknown, FetchBaseQueryError>,
    tagTypes: ['Store'],
    endpoints: (builder) => ({
        /**
         * For valid response try integer IDs with value < 1000. Anything above 1000 or nonintegers will generate API errors
         * Delete purchase order by ID
         */
        deleteOrder: builder.mutation<void, DeleteOrderRequest>({
            query: ({ orderId }) => {
                if (orderId === null || orderId === undefined) {
                    throw new runtime.RequiredError('orderId', 'Required parameter orderId was null or undefined when calling deleteOrder.');
                }


                const headerParameters: runtime.HttpHeaders = {};


                return {
                    url: `/store/order/{orderId}`.replace('orderId', encodeURIComponent(String(orderId))),
                    method: 'DELETE',
                    headers: headerParameters,
                };
            },
        }),
        /**
         * Returns a map of status codes to quantities
         * Returns pet inventories by status
         */
        getInventory: builder.query<{ [key: string]: number; }, void>({
            query: () => {


                const headerParameters: runtime.HttpHeaders = {};


                return {
                    url: `/store/inventory`,
                    method: 'GET',
                    headers: headerParameters,
                };
            },
        }),
        /**
         * For valid response try integer IDs with value <= 5 or > 10. Other values will generate exceptions
         * Find purchase order by ID
         */
        getOrderById: builder.query<Order, GetOrderByIdRequest>({
            query: ({ orderId }) => {
                if (orderId === null || orderId === undefined) {
                    throw new runtime.RequiredError('orderId', 'Required parameter orderId was null or undefined when calling getOrderById.');
                }


                const headerParameters: runtime.HttpHeaders = {};


                return {
                    url: `/store/order/{orderId}`.replace('orderId', encodeURIComponent(String(orderId))),
                    method: 'GET',
                    headers: headerParameters,
                };
            },
            transformResponse: (response: unknown) => {
                return OrderFromJSON(response);
            },
        }),
        /**
         * Place an order for a pet
         */
        placeOrder: builder.mutation<Order, PlaceOrderRequest>({
            query: ({ body }) => {
                if (body === null || body === undefined) {
                    throw new runtime.RequiredError('body', 'Required parameter body was null or undefined when calling placeOrder.');
                }


                const headerParameters: runtime.HttpHeaders = {};
                headerParameters['Content-Type'] = 'application/json';


                return {
                    url: `/store/order`,
                    method: 'POST',
                    headers: headerParameters,
                    body: OrderToJSON(body),
                };
            },
        }),
    }),
});

export const {
    useDeleteOrderMutation,
    useGetInventoryQuery,
    useGetOrderByIdQuery,
    usePlaceOrderMutation,
} = StoreApi;



