/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Petstore
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';
import type { BaseQueryFn, FetchArgs, FetchBaseQueryError } from '@reduxjs/toolkit/query';
import * as runtime from '../runtime';
import type {
    User,
} from '../models/index';
import {
    UserFromJSON,
    UserToJSON,
} from '../models/index';

export interface CreateUserRequest {
    body: User;
}

export interface CreateUsersWithArrayInputRequest {
    body: Array<User>;
}

export interface CreateUsersWithListInputRequest {
    body: Array<User>;
}

export interface DeleteUserRequest {
    username: string;
}

export interface GetUserByNameRequest {
    username: string;
}

export interface LoginUserRequest {
    username: string;
    password: string;
}

export interface UpdateUserRequest {
    username: string;
    body: User;
}


export const UserApi = createApi({
    reducerPath: 'userApi',
    baseQuery: fetchBaseQuery({
        baseUrl: runtime.BASE_PATH,
        prepareHeaders: (headers, { getState }) => {
            return runtime.prepareHeaders(headers);
        },
    }) as BaseQueryFn<FetchArgs, unknown, FetchBaseQueryError>,
    tagTypes: ['User', 'UNKNOWN_ERROR'],
    endpoints: (builder) => ({
        /**
         * This can only be done by the logged in user.
         * Create user
         */
        createUser: builder.mutation<void, CreateUserRequest>({
            query: ({ body }) => {
                if (body === null || body === undefined) {
                    throw new runtime.RequiredError('body', 'Required parameter body was null or undefined when calling createUser.');
                }


                const headerParameters: runtime.HttpHeaders = {};
                headerParameters['Content-Type'] = 'application/json';


                return {
                    url: `/user`,
                    method: 'POST',
                    headers: headerParameters,
                    body: UserToJSON(body),
                };
            },
            invalidatesTags: (result) =>
                result
                    ? ['User']
                    : [],
        }),
        /**
         * Creates list of users with given input array
         */
        createUsersWithArrayInput: builder.mutation<void, CreateUsersWithArrayInputRequest>({
            query: ({ body }) => {
                if (body === null || body === undefined) {
                    throw new runtime.RequiredError('body', 'Required parameter body was null or undefined when calling createUsersWithArrayInput.');
                }


                const headerParameters: runtime.HttpHeaders = {};
                headerParameters['Content-Type'] = 'application/json';


                return {
                    url: `/user/createWithArray`,
                    method: 'POST',
                    headers: headerParameters,
                    body: body?.map(UserToJSON),
                };
            },
            invalidatesTags: (result) =>
                result
                    ? ['User']
                    : [],
        }),
        /**
         * Creates list of users with given input array
         */
        createUsersWithListInput: builder.mutation<void, CreateUsersWithListInputRequest>({
            query: ({ body }) => {
                if (body === null || body === undefined) {
                    throw new runtime.RequiredError('body', 'Required parameter body was null or undefined when calling createUsersWithListInput.');
                }


                const headerParameters: runtime.HttpHeaders = {};
                headerParameters['Content-Type'] = 'application/json';


                return {
                    url: `/user/createWithList`,
                    method: 'POST',
                    headers: headerParameters,
                    body: body?.map(UserToJSON),
                };
            },
            invalidatesTags: (result) =>
                result
                    ? ['User']
                    : [],
        }),
        /**
         * This can only be done by the logged in user.
         * Delete user
         */
        deleteUser: builder.mutation<void, DeleteUserRequest>({
            query: ({ username }) => {
                if (username === null || username === undefined) {
                    throw new runtime.RequiredError('username', 'Required parameter username was null or undefined when calling deleteUser.');
                }


                const headerParameters: runtime.HttpHeaders = {};


                return {
                    url: `/user/{username}`.replace('username', encodeURIComponent(String(username))),
                    method: 'DELETE',
                    headers: headerParameters,
                };
            },
            invalidatesTags: (result, error, { username }) =>
                result
                    ? [{ type: 'User' as const, id: username }, 'User']
                    : [],
        }),
        /**
         * Get user by user name
         */
        getUserByName: builder.query<User, GetUserByNameRequest>({
            query: ({ username }) => {
                if (username === null || username === undefined) {
                    throw new runtime.RequiredError('username', 'Required parameter username was null or undefined when calling getUserByName.');
                }


                const headerParameters: runtime.HttpHeaders = {};


                return {
                    url: `/user/{username}`.replace('username', encodeURIComponent(String(username))),
                    method: 'GET',
                    headers: headerParameters,
                };
            },
            transformResponse: (response: unknown) => {
                return UserFromJSON(response);
            },
            providesTags: (result, error, { username }) =>
                result
                    ? [{ type: 'User' as const, id: username }]
                    : ['UNKNOWN_ERROR'],
        }),
        /**
         * Logs user into the system
         */
        loginUser: builder.query<string, LoginUserRequest>({
            query: ({ username, password }) => {
                if (username === null || username === undefined) {
                    throw new runtime.RequiredError('username', 'Required parameter username was null or undefined when calling loginUser.');
                }
                if (password === null || password === undefined) {
                    throw new runtime.RequiredError('password', 'Required parameter password was null or undefined when calling loginUser.');
                }

                const queryParameters: Record<string, any> = {};
                if (username !== undefined) {
                    queryParameters['username'] = username;
                }
                if (password !== undefined) {
                    queryParameters['password'] = password;
                }

                const headerParameters: runtime.HttpHeaders = {};


                return {
                    url: `/user/login`,
                    method: 'GET',
                    headers: headerParameters,
                    params: queryParameters,
                };
            },
            providesTags: (result) =>
                result
                    ? ['User']
                    : ['UNKNOWN_ERROR'],
        }),
        /**
         * Logs out current logged in user session
         */
        logoutUser: builder.query<void, void>({
            query: () => {


                const headerParameters: runtime.HttpHeaders = {};


                return {
                    url: `/user/logout`,
                    method: 'GET',
                    headers: headerParameters,
                };
            },
            providesTags: (result) =>
                result
                    ? ['User']
                    : ['UNKNOWN_ERROR'],
        }),
        /**
         * This can only be done by the logged in user.
         * Updated user
         */
        updateUser: builder.mutation<void, UpdateUserRequest>({
            query: ({ username, body }) => {
                if (username === null || username === undefined) {
                    throw new runtime.RequiredError('username', 'Required parameter username was null or undefined when calling updateUser.');
                }
                if (body === null || body === undefined) {
                    throw new runtime.RequiredError('body', 'Required parameter body was null or undefined when calling updateUser.');
                }


                const headerParameters: runtime.HttpHeaders = {};
                headerParameters['Content-Type'] = 'application/json';


                return {
                    url: `/user/{username}`.replace('username', encodeURIComponent(String(username))),
                    method: 'PUT',
                    headers: headerParameters,
                    body: UserToJSON(body),
                };
            },
            invalidatesTags: (result, error, { username }) =>
                result
                    ? [{ type: 'User' as const, id: username }, 'User']
                    : [],
        }),
    }),
});

export const {
    useCreateUserMutation,
    useCreateUsersWithArrayInputMutation,
    useCreateUsersWithListInputMutation,
    useDeleteUserMutation,
    useGetUserByNameQuery,
    useLoginUserQuery,
    useLogoutUserQuery,
    useUpdateUserMutation,
} = UserApi;



