/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Petstore
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';
import type { BaseQueryFn, FetchArgs, FetchBaseQueryError } from '@reduxjs/toolkit/query';
import * as runtime from '../runtime';
import type { BffErrorResponse } from '../runtime';
import { Configuration, DefaultConfig } from '../runtime';
import type {
    User,
} from '../models/index';
import {
    UserFromJSON,
    UserToJSON,
} from '../models/index';

export interface CreateUserRequest {
    body: User;
}

export interface CreateUsersWithArrayInputRequest {
    body: Array<User>;
}

export interface CreateUsersWithListInputRequest {
    body: Array<User>;
}

export interface DeleteUserRequest {
    username: string;
}

export interface GetUserByNameRequest {
    username: string;
}

export interface LoginUserRequest {
    username: string;
    password: string;
}

export interface UpdateUserRequest {
    username: string;
    body: User;
}


const userApiBaseQuery: BaseQueryFn<FetchArgs, unknown, FetchBaseQueryError | BffErrorResponse> = async (args: FetchArgs, api: any, extraOptions: { configuration?: Configuration }) => {
    const configuration = extraOptions?.configuration || DefaultConfig;
    const rawBaseQuery = fetchBaseQuery({
        baseUrl: configuration.basePath,
        prepareHeaders: (headers) => {
            if (configuration.username !== undefined || configuration.password !== undefined) {
                headers.set('Authorization', 'Basic ' + btoa(configuration.username + ':' + configuration.password));
            }
            if (configuration.accessToken) {
                headers.set('Authorization', `Bearer ${configuration.accessToken()}`);
            }
            if (configuration.apiKey) {
                headers.set('api_key', configuration.apiKey('api_key'));
            }
            if (configuration.headers) {
                Object.entries(configuration.headers).forEach(([key, value]) => {
                    headers.set(key, value);
                });
            }
            return headers;
        },
    });
    const result = await rawBaseQuery(args, api, extraOptions);
    if (result.data && runtime.isBffError(result.data)) {
        return { error: result.data as BffErrorResponse };
    }
    return result;
};

export const UserApi = createApi({
    reducerPath: 'userApi',
    baseQuery: userApiBaseQuery,
    tagTypes: ['User'],
    endpoints: (builder) => ({
        /**
         * This can only be done by the logged in user.
         * Create user
         */
        createUser: builder.mutation<void, CreateUserRequest>({
            query: ({ body }) => {

                const headerParameters: runtime.HttpHeaders = {};
                headerParameters['Content-Type'] = 'application/json';


                return {
                    url: `/user`,
                    method: 'POST',
                    headers: headerParameters,
                    body: UserToJSON(body),
                };
            },
            invalidatesTags: ['User'],
        }),
        /**
         * Creates list of users with given input array
         */
        createUsersWithArrayInput: builder.mutation<void, CreateUsersWithArrayInputRequest>({
            query: ({ body }) => {

                const headerParameters: runtime.HttpHeaders = {};
                headerParameters['Content-Type'] = 'application/json';


                return {
                    url: `/user/createWithArray`,
                    method: 'POST',
                    headers: headerParameters,
                    body: body?.map(UserToJSON),
                };
            },
            invalidatesTags: ['User'],
        }),
        /**
         * Creates list of users with given input array
         */
        createUsersWithListInput: builder.mutation<void, CreateUsersWithListInputRequest>({
            query: ({ body }) => {

                const headerParameters: runtime.HttpHeaders = {};
                headerParameters['Content-Type'] = 'application/json';


                return {
                    url: `/user/createWithList`,
                    method: 'POST',
                    headers: headerParameters,
                    body: body?.map(UserToJSON),
                };
            },
            invalidatesTags: ['User'],
        }),
        /**
         * This can only be done by the logged in user.
         * Delete user
         */
        deleteUser: builder.mutation<void, DeleteUserRequest>({
            query: ({ username }) => {

                const headerParameters: runtime.HttpHeaders = {};


                return {
                    url: `/user/{username}`.replace('{username}', encodeURIComponent(String(username))),
                    method: 'DELETE',
                    headers: headerParameters,
                };
            },
            invalidatesTags: ['User'],
        }),
        /**
         * Get user by user name
         */
        getUserByName: builder.query<User, GetUserByNameRequest>({
            query: ({ username }) => {

                const headerParameters: runtime.HttpHeaders = {};


                return {
                    url: `/user/{username}`.replace('{username}', encodeURIComponent(String(username))),
                    method: 'GET',
                    headers: headerParameters,
                };
            },
            providesTags: ['User'],
        }),
        /**
         * Logs user into the system
         */
        loginUser: builder.query<string, LoginUserRequest>({
            query: ({ username, password }) => {

                const queryParameters: Record<string, any> = {};
                if (username !== undefined) {
                    queryParameters['username'] = username;
                }
                if (password !== undefined) {
                    queryParameters['password'] = password;
                }

                const headerParameters: runtime.HttpHeaders = {};


                return {
                    url: `/user/login`,
                    method: 'GET',
                    headers: headerParameters,
                    params: queryParameters,
                };
            },
            providesTags: ['User'],
        }),
        /**
         * Logs out current logged in user session
         */
        logoutUser: builder.query<void, void>({
            query: () => {

                const headerParameters: runtime.HttpHeaders = {};


                return {
                    url: `/user/logout`,
                    method: 'GET',
                    headers: headerParameters,
                };
            },
            providesTags: ['User'],
        }),
        /**
         * This can only be done by the logged in user.
         * Updated user
         */
        updateUser: builder.mutation<void, UpdateUserRequest>({
            query: ({ username, body }) => {

                const headerParameters: runtime.HttpHeaders = {};
                headerParameters['Content-Type'] = 'application/json';


                return {
                    url: `/user/{username}`.replace('{username}', encodeURIComponent(String(username))),
                    method: 'PUT',
                    headers: headerParameters,
                    body: UserToJSON(body),
                };
            },
            invalidatesTags: ['User'],
        }),
    }),
});

export const {
    useCreateUserMutation,
    useCreateUsersWithArrayInputMutation,
    useCreateUsersWithListInputMutation,
    useDeleteUserMutation,
    useGetUserByNameQuery,
    useLoginUserQuery,
    useLogoutUserQuery,
    useUpdateUserMutation,
} = UserApi;
